services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ivgk-whatsapp-frontend
    env_file:
      - .env.prod
    ports:
      - "3016:3000"
    restart: unless-stopped
    networks:
      - IVGK-proxy

networks:
  IVGK-proxy:
    external: true

