services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXT_PUBLIC_META_APP_ID: ${NEXT_PUBLIC_META_APP_ID}
        NEXT_PUBLIC_META_CONFIG_ID: ${NEXT_PUBLIC_META_CONFIG_ID}
    container_name: ivgk-whatsapp-frontend
    env_file:
      - .env.prod
    ports:
      - "3016:3000"
    restart: unless-stopped
    networks:
      - IVGK-proxy

networks:
  IVGK-proxy:
    external: true

